kimspec_order = (
    "content-origin",
    "content-other-locations",
    "contributor-id",
    "date",
    "description",
    "developer",
    "disclaimer",
    "doi",
    "domain",
    "executables" "extended-id",
    "funding",
    "implementer",
    "kim-api-version",
    "kim-item-type",
    "license",
    "maintainer-id",
    "model-driver",
    "potential-type",
    "simulator-name",
    "simulator-potential",
    "simulator-potential-compatibility",
    "source-citations",
    "species",
    "title",
    "training",
)

kimspec_strings = (
    "content-origin",
    "content-other-locations",
    "date",
    "description",
    "disclaimer",
    "doi",
    "domain",
    "extended-id",
    "kim-api-version",
    "kim-item-type",
    "maintainer-id",
    "model-driver",
    "potential-type",
    "simulator-name",
    "simulator-potential",
    "title",
)

# The type specified in these dicts is what the inner type of the kimspec array should be
kimspec_arrays = {
    "developer": str,
    "execuatbles": str,
    "funding": dict,
    "implementer": str,
    "simulator_potential_compatibility": dict,
    "source-citations": dict,  # BibTex style edn dicts of citations
    "species": str,
    "training": str,
}
# TODO: copy crossref query from webapp?
kimspec_funding_keys_required = {
    "funder-name": True,
    "award-number": False,
    "award-uri": False,
    "award-title": False,
}

kimspec_simulator_potential_compatibility_keys_required = {
    "simulator-name": True,
    "simulator-potential": True,
    "compatibility": True,
    "compatibility-notes": False,
}

KIMkit_item_type_key_requirements = {
    "portable-model": {
        "required": [
            "description",
            "developer",
            "extended-id",
            "implementer",
            "kim-api-version",
            "potential-type",
            "species",
            "title",
        ],
        "optional": [
            "content-origin",
            "content-other-locations",
            "contributor-id",
            "disclaimer",
            "doi",
            "domain",
            "executables",
            "funding",
            "maintainer-id",
            "model-driver",
            "date",
            "source-citations",
            "training",
        ],
    },
    "simulator-model": {
        "required": [
            "description",
            "developer",
            "extended-id",
            "implementer",
            "kim-api-version",
            "potential-type",
            "species",
            "simulator-name",
            "simulator-potential",
            "title",
        ],
        "optional": [
            "content-origin",
            "content-other-locations",
            "contributor-id",
            "disclaimer",
            "doi",
            "domain",
            "executables",
            "funding",
            "maintainer-id",
            "date",
            "source-citations",
            "training",
        ],
    },
    "model-driver": {
        "required": [
            "description",
            "developer",
            "extended-id",
            "implementer",
            "kim-api-version",
            "title",
        ],
        "optional": [
            "content-origin",
            "content-other-locations",
            "contributor-id",
            "disclaimer",
            "doi",
            "domain",
            "executables",
            "funding",
            "maintainer-id",
            "date",
            "simulator-potential-compatibility",
            "source-citations",
        ],
    },
}
