[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "kimkit"
dynamic = ["version"]
dependencies=["pytz", "kim_edn", "packaging", "pygments", "pymongo"]